[theme]
base = "dark"
primaryColor = "#8b5cf6"
backgroundColor = "#07060d"
secondaryBackgroundColor = "#14101f"
textColor = "#f4f5fb"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
